// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafehavenPMS.Data;

#nullable disable

namespace SafehavenPMS.Migrations
{
    [DbContext(typeof(SafehavenPMSContext))]
    [Migration("20250916015128_MakePsyProblemListIdNullablejhgsasd")]
    partial class MakePsyProblemListIdNullablejhgsasd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafehavenPMS.Models.AdministrationLog", b =>
                {
                    b.Property<int>("AdministrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdministrationId"));

                    b.Property<DateTime>("AdministrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("BedtimeTaken")
                        .HasColumnType("bit");

                    b.Property<bool>("BreakfastTaken")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DinnerTaken")
                        .HasColumnType("bit");

                    b.Property<bool>("LunchTaken")
                        .HasColumnType("bit");

                    b.Property<int>("MedicationOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicineId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int");

                    b.HasKey("AdministrationId");

                    b.HasIndex("MedicationOrderId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PatientId");

                    b.ToTable("AdministrationLogs");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Admission", b =>
                {
                    b.Property<int>("AdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmissionId"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId1")
                        .HasColumnType("int");

                    b.Property<int?>("PhysicianId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<int?>("PsychometricianId")
                        .HasColumnType("int");

                    b.Property<int?>("RecoveryCoachId")
                        .HasColumnType("int");

                    b.Property<int?>("SocialWorkerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdmissionId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientId1");

                    b.HasIndex("PhysicianId");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("PsychometricianId");

                    b.HasIndex("RecoveryCoachId");

                    b.HasIndex("SocialWorkerId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Availability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<int>("ClinicalStaffID")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SlotDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("ClinicalStaffID");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("SafehavenPMS.Models.ClinicalStaff", b =>
                {
                    b.Property<int>("ClinicalStaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicalStaffID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRC_Licensed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClinicalStaffID");

                    b.ToTable("ClinicalStaffs");
                });

            modelBuilder.Entity("SafehavenPMS.Models.ClinicalStaffPatient", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ClinicalStaffId")
                        .HasColumnType("int");

                    b.Property<int?>("AdmissionId")
                        .HasColumnType("int");

                    b.HasKey("PatientId", "ClinicalStaffId");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("ClinicalStaffId");

                    b.ToTable("ClinicalStaffPatients");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialAssessmentFormId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiagnosisId");

                    b.HasIndex("InitialAssessmentFormId")
                        .IsUnique();

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("SafehavenPMS.Models.DischargedPatient", b =>
                {
                    b.Property<int>("DischargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DischargeId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DischargeId");

                    b.HasIndex("PatientId");

                    b.ToTable("DischargedPatients");
                });

            modelBuilder.Entity("SafehavenPMS.Models.DrugUse", b =>
                {
                    b.Property<int>("DrugUseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugUseId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectsWhenHigh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectsWhenWanes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialAssessmentFormId")
                        .HasColumnType("int");

                    b.Property<string>("QuantityPerDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstanceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrugUseId");

                    b.HasIndex("InitialAssessmentFormId");

                    b.ToTable("DrugUses");
                });

            modelBuilder.Entity("SafehavenPMS.Models.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntakeFormId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientIntakeIntakeFormsId")
                        .HasColumnType("int");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IntakeFormId");

                    b.HasIndex("PatientIntakeIntakeFormsId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProblemListId")
                        .HasColumnType("int");

                    b.Property<int?>("PsyProblemListId")
                        .HasColumnType("int");

                    b.Property<int?>("PsychiatricAssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GoalId");

                    b.HasIndex("ProblemListId");

                    b.HasIndex("PsyProblemListId");

                    b.HasIndex("PsychiatricAssessmentId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("SafehavenPMS.Models.HistoryPresent", b =>
                {
                    b.Property<int>("HistoryPresentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryPresentId"));

                    b.Property<string>("AmountConsumedFirstUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoryOfImprisonment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialAssessmentFormId")
                        .HasColumnType("int");

                    b.Property<string>("LastUseOfSubstance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfPeopleFirstUse")
                        .HasColumnType("int");

                    b.Property<string>("OnsetOfDrugUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousDrugRehab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForFirstUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoInvitedFirstUse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HistoryPresentId");

                    b.HasIndex("InitialAssessmentFormId")
                        .IsUnique();

                    b.ToTable("HistoryPresents");
                });

            modelBuilder.Entity("SafehavenPMS.Models.InitialAssessmentForm", b =>
                {
                    b.Property<int>("InitialAssessmentFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InitialAssessmentFormId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InitialAssessmentFormId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("PatientId1");

                    b.ToTable("InitialAssessmentForms");
                });

            modelBuilder.Entity("SafehavenPMS.Models.IntakeForm", b =>
                {
                    b.Property<int>("IntakeFormsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntakeFormsId"));

                    b.Property<string>("AccompaniedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Affiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CouncilorImpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherFamilyDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentingComplaint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemPresentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntakeFormsId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("IntakeForms");
                });

            modelBuilder.Entity("SafehavenPMS.Models.MedicalAllergy", b =>
                {
                    b.Property<int>("MedicalAllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalAllergyId"));

                    b.Property<string>("AllergyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllergyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialAssessmentFormId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicalAllergyId");

                    b.HasIndex("InitialAssessmentFormId");

                    b.ToTable("MedicalAllergies");
                });

            modelBuilder.Entity("SafehavenPMS.Models.MedicalHistory", b =>
                {
                    b.Property<int>("MedicalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalHistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialAssessmentFormId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAsthmatic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDiabetic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHypertensive")
                        .HasColumnType("bit");

                    b.Property<bool>("MaternalDiabetic")
                        .HasColumnType("bit");

                    b.Property<bool>("MaternalHypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("MaternalNone")
                        .HasColumnType("bit");

                    b.Property<string>("OtherConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PaternalDiabetic")
                        .HasColumnType("bit");

                    b.Property<bool>("PaternalHypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("PaternalNone")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicalHistoryId");

                    b.HasIndex("InitialAssessmentFormId")
                        .IsUnique();

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("SafehavenPMS.Models.MedicationOrder", b =>
                {
                    b.Property<int>("MedicationOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationOrderId"));

                    b.Property<bool>("Bedtime")
                        .HasColumnType("bit");

                    b.Property<bool>("Breakfast")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DaysInterval")
                        .HasColumnType("int");

                    b.Property<bool>("Dinner")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DiscontinueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lunch")
                        .HasColumnType("bit");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<bool>("NoDiscontinueDate")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ScheduledType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnitPerDose")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicationOrderId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicationOrders");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Strength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicineId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("SafehavenPMS.Models.MentalStatusExamination", b =>
                {
                    b.Property<int>("MentalStatusExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MentalStatusExaminationId"));

                    b.Property<bool>("AffectAppropriate")
                        .HasColumnType("bit");

                    b.Property<bool>("AffectBlunted")
                        .HasColumnType("bit");

                    b.Property<bool>("AffectFlat")
                        .HasColumnType("bit");

                    b.Property<bool>("AffectInappropriate")
                        .HasColumnType("bit");

                    b.Property<string>("AffectOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BehaviorCooperative")
                        .HasColumnType("bit");

                    b.Property<string>("BehaviorOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BehaviorPreoccupied")
                        .HasColumnType("bit");

                    b.Property<bool>("BehaviorRelaxed")
                        .HasColumnType("bit");

                    b.Property<bool>("BehaviorSuspicious")
                        .HasColumnType("bit");

                    b.Property<bool>("CognitionConfused")
                        .HasColumnType("bit");

                    b.Property<bool>("CognitionConscious")
                        .HasColumnType("bit");

                    b.Property<bool>("CognitionDrowsy")
                        .HasColumnType("bit");

                    b.Property<string>("CognitionOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GeneralAppearanceDishevelled")
                        .HasColumnType("bit");

                    b.Property<bool>("GeneralAppearanceInappropriate")
                        .HasColumnType("bit");

                    b.Property<bool>("GeneralAppearanceNeat")
                        .HasColumnType("bit");

                    b.Property<string>("GeneralAppearanceOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialAssessmentFormId")
                        .HasColumnType("int");

                    b.Property<bool>("InsightFair")
                        .HasColumnType("bit");

                    b.Property<bool>("InsightGood")
                        .HasColumnType("bit");

                    b.Property<bool>("InsightPoor")
                        .HasColumnType("bit");

                    b.Property<bool>("JudgementFair")
                        .HasColumnType("bit");

                    b.Property<bool>("JudgementGood")
                        .HasColumnType("bit");

                    b.Property<bool>("JudgementPoor")
                        .HasColumnType("bit");

                    b.Property<bool>("MemoryLongTerm")
                        .HasColumnType("bit");

                    b.Property<string>("MemoryOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MemoryShortTerm")
                        .HasColumnType("bit");

                    b.Property<bool>("MoodAngry")
                        .HasColumnType("bit");

                    b.Property<bool>("MoodAnxious")
                        .HasColumnType("bit");

                    b.Property<bool>("MoodFearful")
                        .HasColumnType("bit");

                    b.Property<bool>("MoodHappy")
                        .HasColumnType("bit");

                    b.Property<bool>("MoodHelpless")
                        .HasColumnType("bit");

                    b.Property<bool>("MoodHopeless")
                        .HasColumnType("bit");

                    b.Property<string>("MoodOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MoodSad")
                        .HasColumnType("bit");

                    b.Property<bool>("OrientationDisorientedToPerson")
                        .HasColumnType("bit");

                    b.Property<bool>("OrientationDisorientedToPlace")
                        .HasColumnType("bit");

                    b.Property<bool>("OrientationDisorientedToTime")
                        .HasColumnType("bit");

                    b.Property<bool>("OrientationOrientedToPerson")
                        .HasColumnType("bit");

                    b.Property<bool>("OrientationOrientedToPlace")
                        .HasColumnType("bit");

                    b.Property<bool>("OrientationOrientedToTime")
                        .HasColumnType("bit");

                    b.Property<string>("OrientationOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PerceptionsAuditoryHallucinations")
                        .HasColumnType("bit");

                    b.Property<bool>("PerceptionsDelusions")
                        .HasColumnType("bit");

                    b.Property<bool>("PerceptionsIllusions")
                        .HasColumnType("bit");

                    b.Property<string>("PerceptionsOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PerceptionsParanoia")
                        .HasColumnType("bit");

                    b.Property<bool>("PerceptionsSuicidalAttempt")
                        .HasColumnType("bit");

                    b.Property<bool>("PerceptionsSuicidalIdeations")
                        .HasColumnType("bit");

                    b.Property<bool>("PerceptionsVisualHallucinations")
                        .HasColumnType("bit");

                    b.Property<bool>("SpeechIncoherent")
                        .HasColumnType("bit");

                    b.Property<bool>("SpeechNormal")
                        .HasColumnType("bit");

                    b.Property<string>("SpeechOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SpeechRapid")
                        .HasColumnType("bit");

                    b.Property<bool>("SpeechSlow")
                        .HasColumnType("bit");

                    b.Property<bool>("ThoughtsFlightOfIdeas")
                        .HasColumnType("bit");

                    b.Property<bool>("ThoughtsNormal")
                        .HasColumnType("bit");

                    b.Property<string>("ThoughtsOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThoughtsPreoccupied")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ViolenceClenchedFist")
                        .HasColumnType("bit");

                    b.Property<string>("ViolenceOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ViolenceRaisedVoice")
                        .HasColumnType("bit");

                    b.Property<bool>("ViolenceRelaxed")
                        .HasColumnType("bit");

                    b.Property<bool>("ViolenceRestless")
                        .HasColumnType("bit");

                    b.HasKey("MentalStatusExaminationId");

                    b.HasIndex("InitialAssessmentFormId")
                        .IsUnique();

                    b.ToTable("MentalStatusExaminations");
                });

            modelBuilder.Entity("SafehavenPMS.Models.NewAppointment", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("ClinicalStaffID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScheduleTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ClinicalStaffID");

                    b.HasIndex("PatientId");

                    b.ToTable("NewAppointments");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SafehavenPMS.Models.PhysicalExam", b =>
                {
                    b.Property<int>("PhysicalExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicalExamId"));

                    b.Property<string>("AbdomenFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AbdomenNormal")
                        .HasColumnType("bit");

                    b.Property<string>("BP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVSFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CVSNormal")
                        .HasColumnType("bit");

                    b.Property<string>("ChestFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChestNormal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENTFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ENTNormal")
                        .HasColumnType("bit");

                    b.Property<string>("ExtremitiesFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExtremitiesNormal")
                        .HasColumnType("bit");

                    b.Property<string>("GUTFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GUTNormal")
                        .HasColumnType("bit");

                    b.Property<string>("HR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialAssessmentFormId")
                        .HasColumnType("int");

                    b.Property<string>("LungsFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LungsNormal")
                        .HasColumnType("bit");

                    b.Property<string>("O2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkinFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SkinNormal")
                        .HasColumnType("bit");

                    b.Property<string>("Temperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhysicalExamId");

                    b.HasIndex("InitialAssessmentFormId")
                        .IsUnique();

                    b.ToTable("PhysicalExams");
                });

            modelBuilder.Entity("SafehavenPMS.Models.ProblemList", b =>
                {
                    b.Property<int>("ProblemListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProblemListId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialAssessmentFormId")
                        .HasColumnType("int");

                    b.Property<string>("Problem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProblemListId");

                    b.HasIndex("InitialAssessmentFormId");

                    b.ToTable("ProblemLists");
                });

            modelBuilder.Entity("SafehavenPMS.Models.PsyDiagnosisList", b =>
                {
                    b.Property<int>("PsyDiagnosisListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PsyDiagnosisListId"));

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PsychiatricAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("PsyDiagnosisListId");

                    b.HasIndex("PsychiatricAssessmentId");

                    b.ToTable("PsyDiagnosisLists");
                });

            modelBuilder.Entity("SafehavenPMS.Models.PsyProblemList", b =>
                {
                    b.Property<int>("PsyProblemListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PsyProblemListId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Problem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PsychiatricAssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PsyProblemListId");

                    b.HasIndex("PsychiatricAssessmentId");

                    b.ToTable("PsyProblemLists");
                });

            modelBuilder.Entity("SafehavenPMS.Models.PsychiatricAssessment", b =>
                {
                    b.Property<int>("PsychiatricAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PsychiatricAssessmentId"));

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("HistoryOfPresentIllness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Impression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MentalStatusExamination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PersonalAndFamilyHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PsychiatricAssessmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("PsychiatricAssessments");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Recommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialAssessmentFormId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecommendationId");

                    b.HasIndex("InitialAssessmentFormId")
                        .IsUnique();

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("SafehavenPMS.Models.SubstanceUseEntry", b =>
                {
                    b.Property<int>("SubstanceUseEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubstanceUseEntryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubstanceUseEntryId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("SubstanceUseEntries");
                });

            modelBuilder.Entity("SafehavenPMS.Models.SurgicalHistory", b =>
                {
                    b.Property<int>("SurgicalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurgicalHistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hospital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialAssessmentFormId")
                        .HasColumnType("int");

                    b.Property<string>("Operation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurgicalHistoryId");

                    b.HasIndex("InitialAssessmentFormId");

                    b.ToTable("SurgicalHistories");
                });

            modelBuilder.Entity("SafehavenPMS.Models.AdministrationLog", b =>
                {
                    b.HasOne("SafehavenPMS.Models.MedicationOrder", "Medication")
                        .WithMany("AdministrationLogs")
                        .HasForeignKey("MedicationOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafehavenPMS.Models.Medicine", null)
                        .WithMany("AdministrationLogs")
                        .HasForeignKey("MedicineId");

                    b.HasOne("SafehavenPMS.Models.Patient", "Patient")
                        .WithMany("AdministrationLogs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Admission", b =>
                {
                    b.HasOne("SafehavenPMS.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafehavenPMS.Models.Patient", null)
                        .WithMany("Admissions")
                        .HasForeignKey("PatientId1");

                    b.HasOne("SafehavenPMS.Models.ClinicalStaff", "Physician")
                        .WithMany()
                        .HasForeignKey("PhysicianId");

                    b.HasOne("SafehavenPMS.Models.ClinicalStaff", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId");

                    b.HasOne("SafehavenPMS.Models.ClinicalStaff", "Psychometrician")
                        .WithMany()
                        .HasForeignKey("PsychometricianId");

                    b.HasOne("SafehavenPMS.Models.ClinicalStaff", "RecoveryCoach")
                        .WithMany()
                        .HasForeignKey("RecoveryCoachId");

                    b.HasOne("SafehavenPMS.Models.ClinicalStaff", "SocialWorker")
                        .WithMany()
                        .HasForeignKey("SocialWorkerId");

                    b.Navigation("Patient");

                    b.Navigation("Physician");

                    b.Navigation("Psychologist");

                    b.Navigation("Psychometrician");

                    b.Navigation("RecoveryCoach");

                    b.Navigation("SocialWorker");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Availability", b =>
                {
                    b.HasOne("SafehavenPMS.Models.ClinicalStaff", "ClinicalStaff")
                        .WithMany("Availabilities")
                        .HasForeignKey("ClinicalStaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClinicalStaff");
                });

            modelBuilder.Entity("SafehavenPMS.Models.ClinicalStaffPatient", b =>
                {
                    b.HasOne("SafehavenPMS.Models.Admission", null)
                        .WithMany("ClinicalStaffPatients")
                        .HasForeignKey("AdmissionId");

                    b.HasOne("SafehavenPMS.Models.ClinicalStaff", "ClinicalStaff")
                        .WithMany("ClinicalStaffPatients")
                        .HasForeignKey("ClinicalStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafehavenPMS.Models.Patient", "Patient")
                        .WithMany("ClinicalStaffPatients")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClinicalStaff");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Diagnosis", b =>
                {
                    b.HasOne("SafehavenPMS.Models.InitialAssessmentForm", "InitialAssessmentForm")
                        .WithOne("Diagnosis")
                        .HasForeignKey("SafehavenPMS.Models.Diagnosis", "InitialAssessmentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialAssessmentForm");
                });

            modelBuilder.Entity("SafehavenPMS.Models.DischargedPatient", b =>
                {
                    b.HasOne("SafehavenPMS.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafehavenPMS.Models.DrugUse", b =>
                {
                    b.HasOne("SafehavenPMS.Models.InitialAssessmentForm", "InitialAssessmentForm")
                        .WithMany("DrugUses")
                        .HasForeignKey("InitialAssessmentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialAssessmentForm");
                });

            modelBuilder.Entity("SafehavenPMS.Models.FamilyMember", b =>
                {
                    b.HasOne("SafehavenPMS.Models.IntakeForm", null)
                        .WithMany("FamilyMembers")
                        .HasForeignKey("IntakeFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafehavenPMS.Models.IntakeForm", "PatientIntake")
                        .WithMany()
                        .HasForeignKey("PatientIntakeIntakeFormsId");

                    b.Navigation("PatientIntake");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Goal", b =>
                {
                    b.HasOne("SafehavenPMS.Models.ProblemList", null)
                        .WithMany("Goals")
                        .HasForeignKey("ProblemListId");

                    b.HasOne("SafehavenPMS.Models.PsyProblemList", "ProblemList")
                        .WithMany("Goals")
                        .HasForeignKey("PsyProblemListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SafehavenPMS.Models.PsychiatricAssessment", null)
                        .WithMany("Goals")
                        .HasForeignKey("PsychiatricAssessmentId");

                    b.Navigation("ProblemList");
                });

            modelBuilder.Entity("SafehavenPMS.Models.HistoryPresent", b =>
                {
                    b.HasOne("SafehavenPMS.Models.InitialAssessmentForm", "InitialAssessmentForm")
                        .WithOne("HistoryPresent")
                        .HasForeignKey("SafehavenPMS.Models.HistoryPresent", "InitialAssessmentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialAssessmentForm");
                });

            modelBuilder.Entity("SafehavenPMS.Models.InitialAssessmentForm", b =>
                {
                    b.HasOne("SafehavenPMS.Models.Patient", "Patient")
                        .WithOne()
                        .HasForeignKey("SafehavenPMS.Models.InitialAssessmentForm", "PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafehavenPMS.Models.Patient", null)
                        .WithMany("InitialAssessmentForms")
                        .HasForeignKey("PatientId1");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafehavenPMS.Models.IntakeForm", b =>
                {
                    b.HasOne("SafehavenPMS.Models.Patient", "Patient")
                        .WithOne("IntakeForm")
                        .HasForeignKey("SafehavenPMS.Models.IntakeForm", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafehavenPMS.Models.MedicalAllergy", b =>
                {
                    b.HasOne("SafehavenPMS.Models.InitialAssessmentForm", "InitialAssessmentForm")
                        .WithMany("MedicalAllergies")
                        .HasForeignKey("InitialAssessmentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialAssessmentForm");
                });

            modelBuilder.Entity("SafehavenPMS.Models.MedicalHistory", b =>
                {
                    b.HasOne("SafehavenPMS.Models.InitialAssessmentForm", "InitialAssessmentForm")
                        .WithOne("MedicalHistory")
                        .HasForeignKey("SafehavenPMS.Models.MedicalHistory", "InitialAssessmentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialAssessmentForm");
                });

            modelBuilder.Entity("SafehavenPMS.Models.MedicationOrder", b =>
                {
                    b.HasOne("SafehavenPMS.Models.Medicine", "Medicine")
                        .WithMany("MedicationOrders")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafehavenPMS.Models.Patient", "Patient")
                        .WithMany("MedicationOrders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafehavenPMS.Models.MentalStatusExamination", b =>
                {
                    b.HasOne("SafehavenPMS.Models.InitialAssessmentForm", "InitialAssessmentForm")
                        .WithOne("MentalStatusExamination")
                        .HasForeignKey("SafehavenPMS.Models.MentalStatusExamination", "InitialAssessmentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialAssessmentForm");
                });

            modelBuilder.Entity("SafehavenPMS.Models.NewAppointment", b =>
                {
                    b.HasOne("SafehavenPMS.Models.ClinicalStaff", "ClinicalStaff")
                        .WithMany("Schedulings")
                        .HasForeignKey("ClinicalStaffID");

                    b.HasOne("SafehavenPMS.Models.Patient", "Patient")
                        .WithMany("NewAppointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClinicalStaff");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafehavenPMS.Models.PhysicalExam", b =>
                {
                    b.HasOne("SafehavenPMS.Models.InitialAssessmentForm", "InitialAssessmentForm")
                        .WithOne("PhysicalExam")
                        .HasForeignKey("SafehavenPMS.Models.PhysicalExam", "InitialAssessmentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialAssessmentForm");
                });

            modelBuilder.Entity("SafehavenPMS.Models.ProblemList", b =>
                {
                    b.HasOne("SafehavenPMS.Models.InitialAssessmentForm", "InitialAssessmentForm")
                        .WithMany("Problems")
                        .HasForeignKey("InitialAssessmentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialAssessmentForm");
                });

            modelBuilder.Entity("SafehavenPMS.Models.PsyDiagnosisList", b =>
                {
                    b.HasOne("SafehavenPMS.Models.PsychiatricAssessment", "PsychiatricAssessment")
                        .WithMany("DiagnosisLists")
                        .HasForeignKey("PsychiatricAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PsychiatricAssessment");
                });

            modelBuilder.Entity("SafehavenPMS.Models.PsyProblemList", b =>
                {
                    b.HasOne("SafehavenPMS.Models.PsychiatricAssessment", "PsychiatricAssessment")
                        .WithMany("ProblemLists")
                        .HasForeignKey("PsychiatricAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PsychiatricAssessment");
                });

            modelBuilder.Entity("SafehavenPMS.Models.PsychiatricAssessment", b =>
                {
                    b.HasOne("SafehavenPMS.Models.Patient", "Patient")
                        .WithMany("PsychiatricAssessments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Recommendation", b =>
                {
                    b.HasOne("SafehavenPMS.Models.InitialAssessmentForm", "InitialAssessmentForm")
                        .WithOne("Recommendation")
                        .HasForeignKey("SafehavenPMS.Models.Recommendation", "InitialAssessmentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialAssessmentForm");
                });

            modelBuilder.Entity("SafehavenPMS.Models.SubstanceUseEntry", b =>
                {
                    b.HasOne("SafehavenPMS.Models.Diagnosis", "Diagnosis")
                        .WithMany("SubstanceUseEntries")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("SafehavenPMS.Models.SurgicalHistory", b =>
                {
                    b.HasOne("SafehavenPMS.Models.InitialAssessmentForm", "InitialAssessmentForm")
                        .WithMany("SurgicalHistories")
                        .HasForeignKey("InitialAssessmentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialAssessmentForm");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Admission", b =>
                {
                    b.Navigation("ClinicalStaffPatients");
                });

            modelBuilder.Entity("SafehavenPMS.Models.ClinicalStaff", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("ClinicalStaffPatients");

                    b.Navigation("Schedulings");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Diagnosis", b =>
                {
                    b.Navigation("SubstanceUseEntries");
                });

            modelBuilder.Entity("SafehavenPMS.Models.InitialAssessmentForm", b =>
                {
                    b.Navigation("Diagnosis");

                    b.Navigation("DrugUses");

                    b.Navigation("HistoryPresent");

                    b.Navigation("MedicalAllergies");

                    b.Navigation("MedicalHistory");

                    b.Navigation("MentalStatusExamination");

                    b.Navigation("PhysicalExam");

                    b.Navigation("Problems");

                    b.Navigation("Recommendation");

                    b.Navigation("SurgicalHistories");
                });

            modelBuilder.Entity("SafehavenPMS.Models.IntakeForm", b =>
                {
                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("SafehavenPMS.Models.MedicationOrder", b =>
                {
                    b.Navigation("AdministrationLogs");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Medicine", b =>
                {
                    b.Navigation("AdministrationLogs");

                    b.Navigation("MedicationOrders");
                });

            modelBuilder.Entity("SafehavenPMS.Models.Patient", b =>
                {
                    b.Navigation("AdministrationLogs");

                    b.Navigation("Admissions");

                    b.Navigation("ClinicalStaffPatients");

                    b.Navigation("InitialAssessmentForms");

                    b.Navigation("IntakeForm")
                        .IsRequired();

                    b.Navigation("MedicationOrders");

                    b.Navigation("NewAppointments");

                    b.Navigation("PsychiatricAssessments");
                });

            modelBuilder.Entity("SafehavenPMS.Models.ProblemList", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("SafehavenPMS.Models.PsyProblemList", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("SafehavenPMS.Models.PsychiatricAssessment", b =>
                {
                    b.Navigation("DiagnosisLists");

                    b.Navigation("Goals");

                    b.Navigation("ProblemLists");
                });
#pragma warning restore 612, 618
        }
    }
}
